### ISSUE TITLE
Вызов функции по таймеру/очереди не обязан возвращать Http.Result

### ISSUE THREAD

**Issue by vitalets** [yandex-cloud/function-ts-types#4]
Сейчас `Http.Result` [явно ожидается](https://github.com/yandex-cloud/function-ts-types/blob/ada4a8e660f8d41fa2e4e49bc61a3e0079e0bd74/src/index.ts#L25), что будет только мешать.

**Comment by DavyJohnes** [comment]
В общем случае для функций вызываемые по триггеру должны возвращать обычный `Http.Result`, в рамках которого  происходит оповещение о наличии или отсутствии ошибок в обработке события. Тот факт что работает и без этого не гарантирует что в ближайшем будущем не может ничего сломаться в этом месте.

**Comment by vitalets** [comment]
> В общем случае для функций вызываемые по триггеру должны возвращать обычный `Http.Result`, в рамках которого происходит оповещение о наличии или отсутствии ошибок в обработке события. Тот факт что работает и без этого не гарантирует что в ближайшем будущем не может ничего сломаться в этом месте.

Разве оповещение о наличии/отсутствии ошибок в обработке события происходит не через бросание исключения?

Или триггер еще смотрит на http status? Если да, то можно ссылочку на доку..

Имхо если функция вызвана не по http, то требовать от нее http ответ не нужно.

**Comment by DavyJohnes** [comment]
> > В общем случае для функций вызываемые по триггеру должны возвращать обычный `Http.Result`, в рамках которого происходит оповещение о наличии или отсутствии ошибок в обработке события. Тот факт что работает и без этого не гарантирует что в ближайшем будущем не может ничего сломаться в этом месте.
> 
> Разве оповещение о наличии/отсутствии ошибок в обработке события происходит не через бросание исключения?
> 
> Или триггер еще смотрит на http status? Если да, то можно ссылочку на доку..
> 
> Имхо если функция вызвана не по http, то требовать от нее http ответ не нужно.

Выбросить исключение - это один из вариантов спровоцировать возврат кода 502 из функции. Если вы хотите вернуть другой код и\или текст ошибки, то это можно сделать через результат функции.
Триггер делает (почти) самый обычный вызов функции (как если бы вы вызвали функцию напрямую по URL) и смотрит на код ответа. Так что тут с точки зрения вызова - это самый обычный http вызов.

**Comment by vitalets** [comment]
> Если вы хотите вернуть другой код и\или текст ошибки, то это можно сделать через результат функции.

Т.е. если например на триггер из YMQ сделать `return {  "statusCode": 502 }`, то очередь посчитает, что сообщение необработано?

> Триггер делает (почти) самый обычный вызов функции (как если бы вы вызвали функцию напрямую по URL) и смотрит на код ответа. Так что тут с точки зрения вызова - это самый обычный http вызов.

Окей. Но с точки зрения разработчика это совсем непохоже на HTTP: я не вижу ни метода, ни хедеров, ни гет-параметров. Поэтому все еще считаю, что требовать для триггеров от функции возвращать HTTP ответ как минимум семантически некорректно. Все-таки HTTP ответ спроектирован под HTTP запрос. Например, когда в запросе пришел неверный урл, я отвечаю 404. А тут если я триггеру отвечу 404 или 302 редиректом - какой это несет смысл?

Вообще в доке было бы полезно описать, что должна возвращать функция в ответ на триггер. [Вот тут](https://cloud.yandex.ru/docs/functions/concepts/trigger/#invoke). Я могу сделать ПР, только сформулировать нужно :)

**Comment by vitalets** [comment]
Кстати обратил внимание, что судя по [доке](https://cloud.yandex.ru/docs/functions/concepts/trigger/#invoke) триггер вызывает функцию с параметром `integration=raw`. Это значит, что статус ответа задать нельзя (он [всегда](https://cloud.yandex.ru/docs/functions/concepts/function-invoke#http) 200). Тогда получается, что утверждение ниже не сработает:
> Если вы хотите вернуть другой код и\или текст ошибки, то это можно сделать через результат функции.

**Comment by DavyJohnes** [comment]
Еще раз почитал код и документацию - вы были правы, я был не прав. От функции вызываемой по триггеру не ожидается явный возврат структуры http ответа. Сейчас внесу правки.
