### ISSUE TITLE
Support WebSocket fields in requestContext

### ISSUE THREAD

**Issue by vitalets** [yandex-cloud/function-ts-types#8]
When using function with WebSocket integration there are several [additional fields](https://cloud.yandex.ru/docs/functions/concepts/function-invoke#request) in `event.requestContext`, e.g. `connectionId`, `eventType`, etc. It would be great to support these fields in typings.

**Comment by esseswann** [comment]
@DavyJohnes Can you assign this to me? I'm preparing a PR
